Initial implementation of EVPN api's and CLI interface
opiproject/godpu pull request #251
Opened 2023-08-03 06:06 UTC by atulpatel261194

Initial implementation of EVPN api's and CLI interface

Changes:
- Added new api's for Logical Bridge, Bridge Port, VRF and SVI
- New CLI interfaces for all the commands
TODO: 
- adding the conf file (usecase: addr field can be place in conf file which is being used in all the commands)  
snap for new cli interface:
![xyz](https://github.com/opiproject/godpu/assets/88648151/05f0e3e9-4b2e-41f4-9d5d-a4106e34b3b9)

2023-08-03 15:33 UTC, mardim91 commented
@atulpatel261194 Thank you for the contribution. Please take a look on the check because they are failing

2023-08-03 16:09 UTC, glimchb commented on network/evpn.go
> +	xpuMgr "github.com/opiproject/opi-api/network/evpn-gw/v1alpha1/gen/go"
I prefer `pb` name

2023-08-03 16:14 UTC, glimchb commented on network/evpn.go
> +func NewLB(addr string) (EvpnClient, error) {
maybe `NewBridge` is a better name

2023-08-08 09:28 UTC, atulpatel261194 commented
> @atulpatel261194 Thank you for the contribution. Please take a look on the check because they are failing

updated the comments , please have a look.

2023-08-08 09:28 UTC, atulpatel261194 commented on network/evpn.go
> +func NewLB(addr string) (EvpnClient, error) {
Done

2023-08-08 09:29 UTC, atulpatel261194 commented on network/evpn.go
> +func NewBP(addr string) (EvpnClient, error) {
Done

2023-08-08 09:29 UTC, atulpatel261194 commented on network/evpn.go
> +	xpuMgr "github.com/opiproject/opi-api/network/evpn-gw/v1alpha1/gen/go"
Done

2023-08-08 11:47 UTC, mardim91 commented on network/evpn.go
> +func NewBP(addr string) (EvpnClient, error) {
I think NewBP is better because it has a direct relation to the API spec as there we have logical bridges and bridgePorts. So it is more clear

2023-08-08 14:33 UTC, glimchb commented on network/evpn.go
> +func NewBP(addr string) (EvpnClient, error) {
`bp` in not clear, too short... let's use full name... if you don't like `NewPort` you can use full name `NewBridgePort` instead...

2023-08-08 14:33 UTC, glimchb commented
@atulpatel261194 still fails ci, please check

2023-08-09 05:48 UTC, atulpatel261194 commented
> @atulpatel261194 still fails ci, please check
> 
> ```
> Error: cmd/evpn-test.go:41:4: log.Printf format %u has unknown verb u
> Error: cmd/evpn-test.go:112:4: log.Printf format %u has unknown verb u
> Error: cmd/evpn-test.go:146:6: log.Printf format %u has unknown verb u
> Error: cmd/evpn-test.go:[18](https://github.com/opiproject/godpu/actions/runs/5795624549/job/15715742815?pr=251#step:5:19)6:4: log.Printf format %u has unknown verb u
> Error: cmd/evpn-test.go:403:4: log.Printf format %u has unknown verb u
> Error: cmd/evpn-test.go:470:4: log.Printf format %u has unknown verb u
> Error: cmd/evpn-test.go:503:6: log.Printf format %u has unknown verb u
> Error: cmd/evpn-test.go:544:4: log.Printf format %u has unknown verb u
> Error: cmd/evpn-test.go:583:4: log.Printf format %d has arg svi.GetSpec().GetVrf() of wrong type string
> Error: cmd/evpn-test.go:653:4: log.Printf format %d has arg svi.GetSpec().GetVrf() of wrong type string
> Error: cmd/evpn-test.go:686:6: log.Printf format %d has arg svi.GetSpec().GetVrf() of wrong type string
> Error: cmd/evpn-test.go:729:4: log.Printf format %d has arg svi.GetSpec().GetVrf() of wrong type string
> ```

I have updated the code. Please Check

2023-08-09 10:16 UTC, mardim91 requested changes
In general LGTM some minor comments

2023-08-09 10:16 UTC, mardim91 commented on network/evpn.go
> +type PbEvpnPortClientGetter func(c grpc.ClientConnInterface) pb.BridgePortServiceClient
PbEvpnBridgeClientGetter - > PbEvpnLogicalBridgeClientGetter

2023-08-09 10:16 UTC, mardim91 commented on network/evpn.go
> +type PbEvpnPortClientGetter func(c grpc.ClientConnInterface) pb.BridgePortServiceClient
PbEvpnPortClientGetter -> PbEvpnBridgePortClientGetter

2023-08-09 10:16 UTC, mardim91 commented on network/evpn.go
> +type PbEvpnPortClientGetter func(c grpc.ClientConnInterface) pb.BridgePortServiceClient
In general update all the Bridge words to LogicalBridge
and all the Port words to BridgePort

2023-08-09 10:40 UTC, mardim91 approved these changes

2023-08-09 15:55 UTC, glimchb commented on network/evpn.go
> +func parseIPAndPrefix(ipPrefixStr string) (*pc.IPPrefix, error) {
no sure this is the best implementation... opened #256

2023-08-09 15:57 UTC, glimchb approved these changes
good first PR
opened few issues https://github.com/opiproject/godpu/issues
to be addressed after the merge

2023-08-09 15:57 UTC, merged